version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis-master:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    command:
      - redis-server
      - --loglevel warning
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-tier
