version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis-master:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-tier
